### ISSUE TITLE
dtrace: failed to initialize dtrace: DTrace device not available on system

### ISSUE THREAD

**Issue by CloudFeng** [openresty/nginx-tutorials#12]
agentzh，您好！最近看您的教程学习Nginx,在看[Nginx 配置指令的执行顺序（四）](https://openresty.org/download/agentzh-nginx-tutorials-zhcn.html#02-NginxDirectiveExecOrder04),对于使用dtrace工具测试demo的性能时候出现了小问题，今天花了很多时间找资料都没有解决，所以想请教您一下。
首先我的环境是：Ubuntu 14.04.2 LTS，3.16.0-37-generic，X86_64.接着，我按照[dtrace4linux](https://github.com/dtrace4linux/linux)安装了dtrace。再着我按照您的教程，将代码敲打进去，因为环境不同，我修改了第一行代码：`#!/usr/sbin/dtrace -s`.最后运行的时候出现的问题如下：
> dtrace: failed to initialize dtrace: DTrace device not available on system.

我想是dtrace安装的问题，所以写了一个简单的测试用例:
```
#!/usr/sbin/dtrace -s
BEGIN
{
	trace("hello");
	exit(0);
}
```

测试是可以通过，但是当我运行`dtrace -l`命令仍旧会出现上述问题。后面我尝试使用一些'dtrace -n'的命令但是仍旧出现同样的问题。最后在网上看到一些solution，但是哪些都是针对非ubuntu系统的，也看到ubuntu上的[一个](http://askubuntu.com/questions/648476/dtrace-failed-to-initialize-dtrace-dtrace-device-not-available-on-system-ubuntu),但是目前没有解决方案。所以冒昧的打扰您！

**Comment by agentzh** [comment]
@CloudFeng I think you should use systemtap-based tools on Linux, which are usually more powerful than dtrace. See

https://openresty.org/#Profiling

https://github.com/openresty/nginx-systemtap-toolkit

https://github.com/openresty/stapxx#samples

BTW, it's recommended to join the openresty (Chinese) mailing list for such discussions. Please see https://openresty.org/#Community Thanks for your cooperation :)
